#!/usr/bin/bash

iDIR="$HOME/.config/hypr/assets/icons"
notify_song="notify-send -h string:x-canonical-private-synchronous:sys-notify-song -u low -i ${iDIR}/music.png"

mesg="`mpc -f "%title% - %artist%" current`"

choosen="$(mpc playlist -f %title% | rofi -theme ~/.config/hypr/assets/themes/music_playlist.rasi -p "Music" -mesg "$mesg" -dmenu -i -selected-row 0 -show-icons false)"

if [[ -n $choosen ]]; then
  mpc searchplay "$choosen" && ${notify_song} "`mpc -f "%title%\n%artist%" current`"
fi
