#!/bin/bash

# Get Volume
get_volume() {
	pamixer --get-volume-human | sed 's/%//'
}

# Increase Volume
increase_volume() {
  [[$(pamixer --get-mute) == true]] && pamixer -u
	pamixer --allow-boost --set-limit 150 -i 5
}

# Decrease Volume
decrease_volume() {
  [[$(pamixer --get-mute) == true]] && pamixer -u
	pamixer --allow-boost --set-limit 150 -d 5
}

# Help
help_command(){
  echo -e "Uso VolumeManager [opcion]
  Opciones:
  --volume, -V: Muestra el volumen actual\n
  --increase, -I: Aumenta el volumen\n
  --decrease, -D: Disminuye el volumen\n
  --toggle, -M: Alterna entre silenciado y sonido\n
  --toggle-mic, -V: Alterna entre silenciado y sonido del microfono\n
  --help: Muestra esta pagina de ayuda\n"
}

case "$1" in
  --volume|-V) get_volume
  ;;
  --increase|-I) increase_volume
  ;;
  --decrease|-D) decrease_volume
  ;;
  --toggle|-M) pamixer --toggle-mute
  ;;
  --toggle-mic|-V) pamixer --default-source --toggle-mute
  ;;
  --help) help_command
  ;;
  *) echo "$(get_volume)%"
  ;;
esac
