#!/bin/bash

# Config File Path
CONFIG_FILE="$HOME/.config/wallpaper.conf"
current_wp="$HOME/.panther"

# Wallpapers Folder
wallpaperFolder="~/.wallpaper"
videoWallpaperFolder="~/Vídeos/wallpaper"

# Lee el modo y la ruta del archivo desde el archivo de configuración
RUTA=$(grep '^ruta=' "$CONFIG_FILE" | cut -d'=' -f2)
BACKEND=$(grep '^backend=' "$CONFIG_FILE" | cut -d'=' -f2)

backend_checker(){
  case "$BACKEND" in
    "swww")
      set_colors "$1"
    ;;
    "mpvpaper")
    ;;
  esac
}

set_colors(){
  
  current_wallpaper="$1" #$(echo "$1" | cut -d'=' -f2 | xargs)
  
  # wal -q -i $current_wallpaper
  
  sed -i "s|^ruta=.*|ruta=$current_wallpaper|" "$CONFIG_FILE"
  
  # ln -sf "$current_wallpaper" "$HOME/.panther/background.png"

  rm -f $current_wp/background.png $current_wp/background-blured.png
  
  magick $current_wallpaper -resize 1366x768\! $current_wp/background.png
  magick $current_wallpaper -resize 1366x768\! -blur 10x10 $current_wp/background-blured.png
}
##############################################################

kill_mpvpaper(){
  if [[ -n  `pgrep mpvpaper` ]]; then
    killall mpvpaper
  fi
}

help_command(){
  echo -e "Uso WallpaperManager [opcion]
  Opciones:
  --video, -V: Abre el selector de wallpaper animados\n
  --static, -S: Abre el selector de wallpaper staticos\n
  --random, -R: Establece un wallpaper aleatorio\n
  --random-video, -A: Establece un wallpaper animado aleatorio\n
  --help, -H: Muestra esta pagina de ayuda\n"
}

main(){
  case "$1" in
    --video|-V)
      kill_mpvpaper
      waypaper --backend mpvpaper --folder $videoWallpaperFolder
      sed -i "s|^backend=.*|backend=mpvpaper|" "$CONFIG_FILE"
    ;;
    --static|-S)
      kill_mpvpaper
      waypaper --backend swww --folder $wallpaperFolder
      sed -i "s|^backend=.*|backend=swww|" "$CONFIG_FILE"
    ;;
    --random|-R)
      kill_mpvpaper
      waypaper --random --backend swww --folder $wallpaperFolder
      sed -i "s|^backend=.*|backend=swww|" "$CONFIG_FILE"
    ;;
    --random-video|-A)
      kill_mpvpaper
      waypaper --random --backend mpvpaper --folder $videoWallpaperFolder
      sed -i "s|^backend=.*|backend=mpvpaper|" "$CONFIG_FILE"
    ;;
    --wall|-w)
      backend_checker "$2"
    ;;
    --help|-H) help_command
    ;;
  esac
}

main "$@"
